# Generated by Django 4.1.3 on 2022-12-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractDetails',
            new_name='ContactDetails',
        ),
    ]
