# Generated by Django 4.1.3 on 2022-11-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
