# Generated by Django 4.1.3 on 2022-11-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
